### ISSUE TITLE
No LICENSE

### ISSUE THREAD

**Issue by tmc** [sethgrid/multibar#6]
Please license your software.

**Comment by wjessop** [comment]
I'd also love it if you could stick a licence in here, thanks!

**Comment by Depado** [comment]
Having a license on that project is necessary. Thanks for the great work :+1:

**Comment by wjessop** [comment]
To make it really easy I've added a license in pull request #11. Thanks!

**Comment by sethgrid** [comment]
Merged PR; thanks everyone
